version: '3.7'
services:
  app:
    image: livehelperchat
    ports:
      - "8080:8080"
      - "3000:80"
    networks:
      - app

  db:
    image: mysql
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    env_file: .env
    networks:
      - app

networks:
  app:
